<?php
	//$loadpage = new loadpage();
	//$loadpage->formfile();

	$v_params = $this->getParams();
	$o_ajuda = $v_params['o_ajuda'];

	/**
	* 
	* @package Admin->Ajuda
	* @author Luis Gustavo Santarosa Pinto
	* @version 1.2.0
	* 
	*/

?>

<form id='ajax_form' method='POST'>
	<div class='modal-header'>
		<button type='button' class='close' data-dismiss='modal' aria-label='Close'><span aria-hidden='true'>&times;</span></button>
		<h4 class='modal-title' id='exampleModalLabel'>Ajuda</h4>
	</div>
	<div class='modal-body'>
		<div class='form-group'>
			<div class='row'>
				<div class='col-md-12'>
					<?php echo $o_ajuda->getConteudo()?>
				</div>								
			</div>
			   
		</div>   
	</div>
	<div class='modal-footer'>
		<button type='button' class='btn btn-default pull-right' data-dismiss='modal'>Voltar</button>
	</div>
</form>